# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-05 16:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='\u540d\u5b57')),
                ('description', models.CharField(default='', max_length=100, verbose_name='\u7b80\u8ff0')),
                ('image', models.ImageField(upload_to='Activity/%Y/%m', verbose_name='\u56fe\u7247')),
                ('restrict_number', models.IntegerField(default=500, verbose_name='\u4eba\u6570\u9650\u5236')),
                ('address', models.CharField(max_length=100, verbose_name='\u8be6\u7ec6\u5730\u70b9')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u53c2\u4e0e\u8d39\u7528')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('added_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6d3b\u52a8',
                'verbose_name_plural': '\u6d3b\u52a8',
            },
        ),
        migrations.CreateModel(
            name='CityDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u57ce\u5e02')),
                ('desc', models.CharField(max_length=200, verbose_name='\u63cf\u8ff0')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '\u57ce\u5e02',
                'verbose_name_plural': '\u57ce\u5e02',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Activity.CityDictionary', verbose_name='\u57ce\u5e02'),
        ),
        migrations.AddField(
            model_name='activity',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u53d1\u8d77\u4eba'),
        ),
    ]
