# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-13 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citydictionary',
            old_name='add_time',
            new_name='added_time',
        ),
    ]
