# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-05 16:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkedActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Activity.Activity', verbose_name='\u6d3b\u52a8')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u6536\u85cf\u7684\u6d3b\u52a8',
                'verbose_name_plural': '\u6536\u85cf\u7684\u6d3b\u52a8',
            },
        ),
        migrations.CreateModel(
            name='MarkedComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Activity.Activity', verbose_name='\u8bf4\u8bf4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u6536\u85cf\u7684\u8bf4\u8bf4',
                'verbose_name_plural': '\u6536\u85cf\u7684\u8bf4\u8bf4',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('system', '\u7cfb\u7edf\u6d88\u606f'), ('user', '\u7528\u6237\u6d88\u606f')], max_length=30, verbose_name='\u6d88\u606f\u7c7b\u578b')),
                ('content', models.CharField(max_length=400, verbose_name='\u6d88\u606f\u5185\u5bb9')),
                ('source', models.CharField(max_length=100, verbose_name='\u6d88\u606f\u6e90')),
                ('has_read', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u8bfb')),
                ('added_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6d88\u606f\u76ee\u6807')),
            ],
            options={
                'verbose_name': '\u63a8\u9001\u6d88\u606f',
                'verbose_name_plural': '\u63a8\u9001\u6d88\u606f',
            },
        ),
        migrations.CreateModel(
            name='ParticipatedActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Activity.Activity', verbose_name='\u6d3b\u52a8')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u53c2\u4e0e\u7684\u6d3b\u52a8',
                'verbose_name_plural': '\u53c2\u4e0e\u7684\u6d3b\u52a8',
            },
        ),
    ]
