pip install django==1.9.8
pip install django_crispy_forms==1.6.1
pip install django_pure_pagination==0.3.0
pip install django_simple_captcha==0.4.6
pip install djangoUeditor==1.8.143
pip install django_formtools==2.0
pip install future==0.16.0
pip install Pillow==4.0.0
pip install httplib2==0.9.2
pip install MySQL_python==1.2.3
