# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-05 16:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u6587\u672c\u5185\u5bb9')),
                ('liked_number', models.IntegerField(default=0, verbose_name='\u70b9\u8d5e\u6570')),
                ('added_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('last_comment', models.IntegerField(default=-1, verbose_name='\u4e0a\u4e00\u6761\u8bc4\u8bba\u7684id')),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u8bf4\u8bf4',
                'verbose_name_plural': '\u8bf4\u8bf4',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_url', models.ImageField(upload_to='comment/%Y/%m', verbose_name='\u8bc4\u8bba\u7684\u56fe\u7247')),
                ('number', models.IntegerField(default=0, verbose_name='\u53f7\u7801')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discovery.Comment', verbose_name='\u8bc4\u8bba')),
            ],
            options={
                'verbose_name': '\u8bc4\u8bba\u7684\u56fe\u7247',
                'verbose_name_plural': '\u8bc4\u8bba\u7684\u56fe\u7247',
            },
        ),
    ]
